language: python
dist: xenial
sudo: required
env:
python:
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - "make setup"
    - "pip install ."
script:
    - "make test"
matrix:
    include:
        - python: "3.6"
          env: LINTING=true
          script:
              - "make lint test"
